Switch to using the elm-format repo.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -22,94 +22,62 @@ fail() {
   exit 1
 }
 
-install_elm() {
+install_elm_format() {
   local install_type=$1
   local version=$2
   local install_path=$3
-  local source_path="${install_path}/bin/elm.gz"
   local destination_path="${install_path}/bin"
+  local source_path="${install_path}/elm-format.tgz"
 
   if [ "$install_type" != "version" ]; then
-    fail "asdf-elm supports release installs only"
+    fail "asdf-elm-format supports release installs only"
   fi
 
-  local converted_version
-  converted_version=$(echo "$version" | tr -d .)
   local platform
   local architecture
 
-  if [ "$converted_version" -ge 0190 ]; then
-    case "$OSTYPE" in
-      darwin*) platform="mac" ;;
-      linux*) platform="linux" ;;
-      *) fail "Unsupported platform" ;;
-    esac
+  case "$OSTYPE" in
+    darwin*)
+      platform="mac"
+      case "$(uname -m)" in
+        x86_64) architecture="x64" ;;
+        arm64) architecture="arm64" ;;
+        *) fail "Unsupported architecture: $(uname -m)" ;;
+      esac
+      ;;
+    linux*)
+      platform="linux"
+      case "$(uname -m)" in
+        x86_64) architecture="x64" ;;
+        aarch64|arm64) architecture="arm64" ;;
+        *) fail "Unsupported architecture: $(uname -m)" ;;
+      esac
+      ;;
+    msys*|cygwin*|mingw*)
+      platform="windows"
+      case "$(uname -m)" in
+        x86_64) architecture="x64" ;;
+        *) fail "Unsupported architecture: $(uname -m)" ;;
+      esac
+      ;;
+    *) fail "Unsupported platform: $OSTYPE" ;;
+  esac
 
-    case "$(uname -m)" in
-      x86_64) architecture="64" ;;
-      arm64) architecture="64" ;;
-      *) fail "Unsupported architecture" ;;
-    esac
-
-    local download_url="https://github.com/elm/compiler/releases/download/${version}/binary-for-${platform}-${architecture}-bit.gz"
-  elif [ "$converted_version" -ge 0180 ]; then
-    case "$OSTYPE" in
-      darwin*) platform="macos" ;;
-      linux*)
-        case "$(uname -m)" in
-          x86_64) platform="linux-64bit" ;;
-          i686) platform="linux-32bit" ;;
-          *) fail "Unsupported architecture" ;;
-        esac
-        ;;
-      *) fail "Unsupported platform" ;;
-    esac
-
-    source_path="${install_path}/bin/elm.tar.gz"
-
-    local download_url="https://github.com/elm-lang/elm-platform/releases/download/0.18.0-exp/elm-platform-${platform}.tar.gz"
-  else
-    case "$OSTYPE" in
-      darwin*) platform="mac" ;;
-      *) fail "Unsupported platform" ;;
-    esac
-
-    pkg_version="${version//%.0$/}"
-    source_path="${install_path}/bin/elm.pkg"
-
-    local download_url="https://github.com/elm/compiler/releases/download/${version}/Elm-Platform-${pkg_version}.pkg"
-  fi
+  local download_url="https://github.com/avh4/elm-format/releases/download/${version}/elm-format-${version}-${platform}-${architecture}.tgz"
 
   (
-    echo "∗ Downloading and installing elm..."
+    echo "∗ Downloading and installing elm-format..."
     mkdir -p "$destination_path"
-    curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-
-    if [ "$converted_version" -ge 0190 ]; then
-      gunzip "$source_path" || fail "Could not uncompress"
-      chmod +x "${destination_path}/elm" || fail "Could not find uncompressed binary"
-      rm -rf "$source_path"
-    elif [ "$converted_version" -ge 0180 ]; then
-      tar zxf "$source_path" -C "$destination_path" || fail "Could not uncompress"
-      chmod +x \
-        "$destination_path/elm" \
-        "$destination_path/elm-make" \
-        "$destination_path/elm-package" \
-        "$destination_path/elm-reactor" \
-        "$destination_path/elm-repl" || fail "Could not find uncompressed binary"
-      rm -rf "$source_path"
-    else
-      unpack_path="${install_path}/unpacked"
-      pkgutil --verbose --expand-full "$source_path" "$unpack_path" &&
-        cp -r "$unpack_path/binaries.pkg/Payload/" "$destination_path" || fail "Could not unpack download"
-      chmod +x \
-        "$destination_path/elm" \
-        "$destination_path/elm-make" \
-        "$destination_path/elm-package" \
-        "$destination_path/elm-reactor" \
-        "$destination_path/elm-repl" || fail "Could not find unpacked binary"
-      rm -rf "$source_path" "$unpack_path"
+    
+    if ! curl --output /dev/null --silent --head --fail "$download_url"; then
+      fail "No binary available for ${platform}-${architecture} at version ${version}
+Check available binaries at: https://github.com/avh4/elm-format/releases/tag/${version}"
     fi
+
+    curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Download failed"
+    tar xzf "$source_path" -C "$destination_path" || fail "Could not uncompress"
+    chmod +x "${destination_path}/elm-format" || fail "Could not make binary executable"
+    rm -f "$source_path"
 
     echo "The installation was successful!"
   ) || (
@@ -118,4 +86,4 @@ install_elm() {
   )
 }
 
-install_elm "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_elm_format "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
